In [1]:
from mpl_toolkits import mplot3d
import numpy as np
import matplotlib.pyplot as plt
import random
import numpy as np
%matplotlib inline

In [2]:
class Particle:
  def __init__(self, x, y):
    self.x = x
    self.y = y
    self.fitness = eggHolder(x,y)
    self.velocity=np.array([0,0])
    self.pibest=np.array([x,y])

In [3]:
def eggHolder(x,y):
    return (-(y+47)*np.sin(np.sqrt(np.abs((x/2)+(y+47))))- (x*np.sin(np.sqrt(np.abs(x-y-47)))))

In [183]:
def holderTable(x,y):
    sxcy = np.sin(x)*np.cos(y)
    expArity = (np.sqrt(x**2 + y**2))/np.pi
    expArity = np.exp(np.abs(1-expArity))
    return -(np.abs(sxcy*expArity))

In [5]:
# Constraints Given
EggHolderXMin = -512
EggHolderXMax = 512
EggHolderYMin = -512
EggHolderYMax = 512
HolderTableXMin = -10
HolderTableXMax = 10 
HolderTableYMin = -10
HolderTableYMax = 10 

In [252]:
# Defining Required Arrays
Population=[]
Averages=[]
gBest = []
bestFitness=[]

In [253]:
# Variable Params
VMax = 2

# c1+c2=4
c1 = 1
c2 = 3

NumberOfIterations = 20
PopulationSize = 10

In [258]:
# Defining Required Funcs
def getVelocity(particle, VMax):
    middleTerm = c1*random.random()*(pbest-particle.pibest)
    endTerm = c2*random.random()*(gbest-particle.pibest)
    calculatedVelocity=particle.velocity+middleTerm+endTerm
    particle.velocity=particle.velocity+middleTerm+endTerm
    return particle.velocity


def getNewPosition(particle,Xmax, Xmin, Ymax, Ymin):
    x,y = getVelocity(particle, VMax)
    if((Xmin <= (x+particle.x) <= Xmax) and (Ymin <= (y+particle.y) <= Ymax)):
        particle.x+=x
        particle.y+=y
    else:
        tempX = particle.x+x
        tempY = particle.y+y
        if(tempX < Xmin):
            particle.x=Xmin
        else:
            particle.x = Xmax
        if(tempY < Ymin):
            particle.y=Ymin
        else:
            particle.y = Ymax
        particle.velocity=np.array([0,0])
        
    return x,y


In [231]:
for particleNumber in range(PopulationSize):
    Population.append(Particle(random.uniform(EggHolderXMin,EggHolderXMax),random.uniform(EggHolderYMin,EggHolderYMax)))
fitneessValues=[]
for particle in Population:
    fitneessValues.append(particle.fitness)
fbest, pbest = min(fitneessValues),np.array([Population[fitneessValues.index(min(fitneessValues))].x,Population[fitneessValues.index(min(fitneessValues))].y])
gbest=pbest
for i in range(NumberOfIterations):
    for particle in Population:
        getNewPosition(particle, EggHolderXMax, EggHolderXMin, EggHolderYMax, EggHolderYMin)
    for particle in Population:
        particle.fitness= eggHolder(particle.x,particle.y) 
    fbest1=fbest
    pbest1=pbest
    fitneessValues=[]
    for particle in Population:
        if(particle.fitness < eggHolder(particle.pibest[0],particle.pibest[1])):
            particle.pibest = np.array([particle.x,particle.y])
        fitneessValues.append(particle.fitness)
    Averages.append((sum(fitneessValues)/len(fitneessValues)))
    fbest, pbest = min(fitneessValues),np.array([Population[fitneessValues.index(min(fitneessValues))].x,Population[fitneessValues.index(min(fitneessValues))].y])
    if fbest<=fbest1:
        gBest.append(gbest)
        bestFitness.append(eggHolder(gbest[0],gbest[1]))
        gbest=pbest   

In [221]:
min(bestFitness)

-879.1324371050658

In [139]:
Population[0].velocity

array([467.43480669,  71.58286826])

In [105]:
Population[0].y

-392.43998680180056

In [104]:
getNewPosition(Population[0],512, EggHolderXMin, EggHolderYMax, EggHolderYMin)

Done


(-172.14525952192454, 51.404223121451714)

In [169]:
gBest

[array([-307.06583922, -484.93998385]),
 array([-305.65463054, -467.09864396]),
 array([-295.65463054, -457.09864396]),
 array([-285.65463054, -447.09864396]),
 array([-418.13203486, -446.50925202]),
 array([-408.13203486, -436.50925202]),
 array([-398.13203486, -426.50925202]),
 array([-398.13203486, -426.50925202]),
 array([-388.13203486, -416.50925202]),
 array([-388.13203486, -416.50925202]),
 array([-388.13203486, -416.50925202]),
 array([-325.53855284,  505.29788094]),
 array([-325.53855284,  505.29788094]),
 array([-325.53855284,  505.29788094]),
 array([326.98881037, 502.26989859]),
 array([460.15446637, 480.89674864]),
 array([460.15446637, 480.89674864]),
 array([460.15446637, 480.89674864]),
 array([499.57330848, 385.80146105]),
 array([509.57330848, 395.80146105]),
 array([509.57330848, 395.80146105]),
 array([509.57330848, 395.80146105]),
 array([509.57330848, 395.80146105]),
 array([509.57330848, 395.80146105]),
 array([509.57330848, 395.80146105]),
 array([509.57330848, 

In [255]:
for particleNumber in range(PopulationSize):
    Population.append(Particle(random.uniform(HolderTableXMin,HolderTableXMax),random.uniform(HolderTableYMin,HolderTableYMax)))
fitneessValues=[]
for particle in Population:
    fitneessValues.append(particle.fitness)
    print(particle.x,particle.y)
print("_"*20)

fbest, pbest = min(fitneessValues),np.array([Population[fitneessValues.index(min(fitneessValues))].x,Population[fitneessValues.index(min(fitneessValues))].y])
gbest=pbest
for i in range(NumberOfIterations):
    for particle in Population:
        getNewPosition(particle, HolderTableXMax, HolderTableXMin, HolderTableYMax, HolderTableYMin)
    for particle in Population:
        particle.fitness= holderTable(particle.x,particle.y) 
    fbest1=fbest
    pbest1=pbest
    fitneessValues=[]
    for particle in Population:
        if(particle.fitness < holderTable(particle.pibest[0],particle.pibest[1])):
            particle.pibest = np.array([particle.x,particle.y])
        fitneessValues.append(particle.fitness)
        print(particle.x,particle.y)
    print("_"*20)
    Averages.append((sum(fitneessValues)/len(fitneessValues)))
    fbest, pbest = min(fitneessValues),np.array([Population[fitneessValues.index(min(fitneessValues))].x,Population[fitneessValues.index(min(fitneessValues))].y])
    if fbest<=fbest1:
        gBest.append(gbest)
        bestFitness.append(holderTable(gbest[0],gbest[1]))
        gbest=pbest

-8.056510967139998 -8.843925315028434
9.720411993614345 -4.734728567245923
4.984548477854865 -9.574325544268039
7.996304576709118 -2.183219361379072
4.7455137441618 5.454159103494138
-6.981191754208698 -0.07198307357621303
5.4368433017473965 -3.605163706381294
3.206081588675211 -1.6940416870338755
-8.995273036991737 -9.45597057473503
-8.88283353095645 7.6513211260570415
____________________
2.162668190820183 2.569479172429636
3.0814798434299018 8.862199558738919
10 10
10 10
4.7455137441618 5.454159103494138
4.9200677740565 5.536416681030535
4.485356979036743 8.863306145712166
5.190893465151824 7.522235739622177
10 10
-0.3217138593606528 6.271097491208166
____________________
10 10
10 10
-3.3482651168457256 -1.5480537032788018
-5.743866072991123 -3.6205723602749096
7.078855432777914 7.47281507806213
10 10
6.025576389768295 6.508863216428852
7.434888974397807 8.565055700785035
4.461368910156571 5.208335412259497
10 10
____________________
10.0 10.0
10.0 10.0
-10 10
-10 -10
10 10
10.0 10.

In [256]:
min(bestFitness)

-15.140223856952058

In [257]:
gBest

[array([4.74551374, 5.4541591 ]),
 array([10, 10]),
 array([10., 10.]),
 array([10., 10.]),
 array([10., 10.]),
 array([10., 10.]),
 array([10., 10.]),
 array([10., 10.]),
 array([10., 10.]),
 array([10., 10.]),
 array([10., 10.]),
 array([10., 10.]),
 array([10., 10.]),
 array([10., 10.]),
 array([10., 10.]),
 array([10., 10.]),
 array([10., 10.]),
 array([10., 10.]),
 array([10., 10.])]

In [184]:
holderTable(8.05502,9.66459)

-19.208502567767606

In [203]:
len(Averages)

200

In [204]:
Averages

[-1.8675996760567184,
 -2.062001574613704,
 -2.6228511916416677,
 -3.766226961732394,
 -3.3255536350454094,
 -3.3255536350454094,
 -3.739915092403082,
 -3.739915092403082,
 -3.3971169940547634,
 -3.3971169940547634,
 -3.4012209609457775,
 -3.683290567938098,
 -3.417534571849642,
 -3.417534571849642,
 -3.3350105597076514,
 -3.3842327223760416,
 -3.564411873282586,
 -3.564411873282586,
 -3.564411873282586,
 -3.564411873282586,
 -3.9683412993896545,
 -3.9683412993896545,
 -3.9683412993896545,
 -3.9683412993896545,
 -3.9683412993896545,
 -3.9683412993896545,
 -3.9683412993896545,
 -3.9683412993896545,
 -3.9683412993896545,
 -3.9683412993896545,
 -3.9683412993896545,
 -3.9683412993896545,
 -4.249918772143674,
 -4.249918772143674,
 -4.249918772143674,
 -4.247848853372196,
 -4.250571636287991,
 -4.250571636287991,
 -4.563292236817548,
 -4.563292236817548,
 -4.563292236817548,
 -4.563292236817548,
 -4.563292236817548,
 -4.563292236817548,
 -4.563292236817548,
 -4.563292236817548,
 -4.563292236